project:
  type: website
  output-dir: docs

website:
  page-navigation: false
  title: "R for Palaeobiologists"
  description: "Palaeoverse: Workshop and Hackathon - University College London, Autumn 2023"
  site-url: https://hackathon.palaeoverse.org
  repo-url: https://github.com/palaeoverse-community/hackathon/
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card: true
  image: "/images/twitter-card.png"
  page-footer:
    border: true
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Lewis A. Jones"
    center: |
      Sponsored by the [Palaeontological Association](https://www.palass.org) and <br>
      the [Paleontological Society](https://www.paleosoc.org)
    background: "lightgrey"

  sidebar:
    background: "lightgrey"
    border: true
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/palaeoverse-community
        text: "GitHub organization"
      - icon: twitter
        href: https://twitter.com/ThePalaeoverse
        text: "Twitter"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - href: schedule.qmd
        text: Schedule
      - href: team.qmd
        text: Organising Team
      - section: "Workshop"
        contents:
          - href: acquisition.qmd
            text: Data acquisition
          - href: preparation.qmd
            text: Data preparation
          - href: visualisation.qmd
            text: Data visualisation
          - href: functions.qmd
            text: Writing functions
          - href: resources.qmd
            text: Resources
      - href: hackathon.qmd
        text: Hackathon
      - href: location.qmd
        text: Getting Here
      - href: accommodation.qmd
        text: Accommodation
      - href: food.qmd
        text: Food and Drink
      - href: entertainment.qmd
        text: Entertainment
      - href: conduct.qmd
        text: Code of Conduct

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

editor: visual